int file1;
char *segmentation_error_file;
int value_one; 
float distance_time;
int rtxtime;
float bbTime;
char a, b, c, d, f, g, h, i, j, k1, l, m, n, o;
char stringB[5000];

void definitionOfClauses();
void definitionFraudlent();
extern void yyerror(const char *);  /* prints grammar violation message */
extern int sym_type(const char *);  /* returns type from symbol table */
static void comment(void);
static void include(void);
static int check_type(void);
void count();
void printLexicalErrors(void);
int yywrap(void);
void printErrors(void);
void search_define_constant();
void format_string(char* string);
void write_to_processed_file(char* string);
void slaitTable(void);
static void conclude(void);
void stringBlind(char* string);
void write_infile(char string);
static int check_divorce(void);
void counterTime();
void definitionOfVariables();
void definition();
extern void yyerrok(const char *);  
int sym(const char *);  
float clauses();
char fraudlent();
void printGramaticalErrors(void);
int yy(void);
void search_constant(int x, char m);
extern void stopErrors(const char *);  
extern int type(const char *);  
extern void comuante_define(void);
void id(int x, char m);
static int check(void);
void count();
float stop(void);
int yywra(void);
void step(void);
void search();
int formag(char* string);
void write_to_processed_file(char* string);
void definitionO();
int udlent();
extern void r(char m);  /* prints grammar violation message */
extern int ef(char m);  /* returns type from symbol table */
void t(void);
static void lookInCicles();
static int lookVariables(int x, char m);
void look();
static int doNothing();
int wrapSandwich(void);
void pr(void);
void constant();
void specialize(float string);
void fileMake(int string, char flat, int x, char m);
